### ISSUE TITLE
Research options for web app hosting

### ISSUE THREAD

**Issue by bmitchinson** [bmitchinson/OpenQ#1]
Research options for where to host Open Q.

May involve:
* Finding a domain name
* Detailed deployment process for the team

**Comment by bmitchinson** [comment]
Looked up firebase and thought it looked cool:

**Comment by jhofmann33** [comment]
> Looked up firebase and thought it looked cool:
https://firebase.google.com/

**Comment by npilafas** [comment]
I found a few web app hosting sites that are free along with Firebase too. The top three I saw were Microsoft Azure, Google Cloud storage and Amazon S3. As for a domain name I found a website with some free ones called dot.tk. I'm a little suspicious about it though cause it's not a secure site and I've never heard of it. Let me know what you all think?

**Comment by bmitchinson** [comment]
@npilafas good find, GCP (Google Cloud), Azure, and S3 are normally easy to set up, but how will we pick between the three?
* What's the cost of hosting on each platform? Are there bandwidth limits?
* What makes them different from one another?
* What are each of their team controls like since everyone on the team will need access to developing the app?
* What's the deployment process like? How will we push our built front end to the platform? Can it be automated from our repo?

**Comment by bmitchinson** [comment]
I found a domain that i'm gonna by for a year for like 4 bucks, so don't worry about domain anymore.
Details to come

**Comment by ralphnahra** [comment]
Also consider adding [Heroku](https://www.heroku.com/) to our list of possibilities. It has a free tier, as well as GitHub integration that allows us to make changes to our code and have it automatically build and run our app so we can review changes and make them live.

**Comment by npilafas** [comment]
Here's some of the stuff I have found:

Azure:
- first 5GB free, .08 cents/GB and .024 cents for File Storage/GB/month
- can connect to GitHub
- Automated deployments with continuous deployment capabilities through GitHub

Amazon:
- 1GB free, .09 cents data transfer/GB, .023 cents File Storage/GB/month
- permissions to share
- Codepipeline deploys files and is automates

Google:
- .11 cents data transfer/GB, .026 cents File Storage/GB/month
- couldn't find anything on teams but I'm sure they have a way to do it
- automated deployment manager

Heroku:
- 1000 hours free while server is running, it 'sleeps' when not in use
- deployments through GitHub integration
- team friendly

Firebase:
- free limited GBs
-team friendly
-own deployment methods

The website below makes some interesting comparisons between all 5 options:

https://blog.patricktriest.com/host-webapps-free/

**Comment by bmitchinson** [comment]
@npilafas 
Great breakdown. That blog post by Triest was really helpful. Learned quite a bit about the different approaches myself, so thanks. Looking forward to deciding how to run it next week 👍

**Comment by bmitchinson** [comment]
Cool heroku feature
![image](https://user-images.githubusercontent.com/33632286/55259465-bb423980-5233-11e9-8148-e3bfd065176b.png)

**Comment by bmitchinson** [comment]
Decided to use Heroku at our last meeting 👍
