### ISSUE TITLE
Should we use a framework for the user interface?

### ISSUE THREAD

**Issue by bmitchinson** [bmitchinson/OpenQ#4]
(The front end of the server)
If so, which framework should we use and why?

**Comment by ralphnahra** [comment]
From personal experience, making a UI with vanilla javascript is annoying, which is gonna be even more true for a more complex application like this. I've used [React](https://reactjs.org/) and recommend it. Also there's a lot of component libraries that make building a UI with React even easier, like the ones listed [here](https://hackernoon.com/23-best-react-ui-component-libraries-and-frameworks-250a81b2ac42).

**Comment by bmitchinson** [comment]
Decided on react since some team members have experience with it at our last meeting 👍
