### ISSUE TITLE
How will we structure our backend?

### ISSUE THREAD

**Issue by bmitchinson** [bmitchinson/OpenQ#5]
* What do we need the backend to accomplish -> What framework/language should it be built in depends on that.
* How does it interact with our database that's stored in the backend

**Comment by ralphnahra** [comment]
So it seems like ideally our backend would be a REST API ([decent explanation here](https://www.quora.com/What-is-a-REST-API)) which would allow us to keep the queue management and all that decoupled from the website's user interface. Making a REST API also makes it trivial to expand our service to something like a mobile application in the future should we choose to do so.

I've found some useful resources for designing APIs/platforms which may come in handy

- https://www.restapitutorial.com/
- [API Design Cheat Sheet](https://github.com/RestCheatSheet/api-cheat-sheet#api-design-cheat-sheet)
- [Platform Design Cheat Sheet](https://github.com/RestCheatSheet/platform-cheat-sheet#platform-building-cheat-sheet)

## Objectives
Our service needs to do the following
- Maintain a queue of songs for an arbitrary number of Raspberry Pi client devices
- Be able to accept new additions to the queue of any client devices
- Be able to accept upvotes/downvotes for individual songs and adjust their place in the queue accordingly


## API Design
I did some brainstorming on our API structure and came up with something like this.

### Main functionality
- `/player/<unique client identifier>`
    - Each OpenQ client (Raspberry Pi) would be accessible by a unique identifier that's created when they 'register' with the service.
    - Upon initial setup, client would register with central service by making an HTTP POST request to `/player`
- `/player/<unique client identifier>/queue`
    - Each player would have a queue 
    - Sending an HTTP GET request here would return a JSON object of all songs currently in the queue
    - Sending an HTTP POST request here with a spotify track ID in the request body would add that track to the queue
- `/player/<unique client identifier>/queue/<number of queue position>`
    - Each song in the queue would have a position denoted by a number
    - Sending an HTTP GET request here would get the info of the song that's in that position (name, artist, album, etc) in JSON format
    - Sending an HTTP POST request here would upvote/downvote the song
- `/player/<unique client identifier>/skip`
    - HTTP POST request here would vote to skip the currently playing song
    - Would be similar to upvote/downvote functionality where there can be votes to skip or keep current song
    - Implementation would be dependent on whether we decide to keep the currently playing song in the queue or not.

### Optional/TBD Functionality
- `/player/<unique client identifier>/log`
    - Sending an HTTP GET request here would return a JSON object of songs that had been played on this client in the past with relevant data (typical song data, time of day played, # of votes, etc.)
    - Timeframe could be configured with query parameters
- `/search/<spotify search terms>`
    - Might be preferable to proxy spotify searches through our application than to have each user query spotify directly
    - Searching through the spotify API could be done with an existing library

## Stack

There are a few popular frameworks that make it relatively easy to set up APIs
- [Express for Node.js](https://expressjs.com/)
- [Flask for Python](http://flask.pocoo.org/)
- More that I don't really know of

I personally have been experimenting with express recently and I enjoy it.

Spotify has a [site for developers](https://developer.spotify.com/) which includes a [list of popular libraries](https://developer.spotify.com/documentation/web-api/libraries/#libraries) that we might want to consider when making our decisions.

**Comment by bmitchinson** [comment]
@Rallph this looks amazing, wonderful work 👍 
REST Sounds great, looking forward to you presenting this info to the rest of the team. Would love the opportunity to learn some express from you myself.

In addition, the linking of popular libraries is perfect. I like the looks of the node one. Hasn't been updated in a while, but hopefully, we can test it out.

**Comment by bmitchinson** [comment]
Running express on GCP is as easy as this: https://cloud.google.com/community/tutorials/run-expressjs-on-google-app-engine

**Comment by bmitchinson** [comment]
Closing this issue, because at this point we should discuss instead how to outline our REST Endpoints in #8 and organizing MongoDB in #7 👍
